# Generated by Django 5.0.4 on 2024-04-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0003_alter_transaction_checkout_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Equipment',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='equipmentmanagement.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='equipmentmanagement.equipment'),
        ),
    ]
