# Generated by Django 5.0.4 on 2024-04-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0004_remove_cart_equipment_remove_cartitem_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='equipmentmanagement.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Maintenance'), ('turn-in', 'Turn-in'), ('returned', 'Returned')], max_length=20),
        ),
    ]
