# Generated by Django 5.0.4 on 2024-04-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0010_alter_cart_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='equipmentmanagement.userprofile'),
        ),
    ]
