# Generated by Django 5.0.4 on 2024-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentmanagement', '0011_alter_cart_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
